sudo: required
services:
- docker

env:
- DOCKER_IMAGE_NAME="r.3r1.co/3r1co/copy-docker-image:$TRAVIS_BUILD_NUMBER"

script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" r.3r1.co
- docker build -t $DOCKER_IMAGE_NAME .

after_success:
- docker push $DOCKER_IMAGE_NAME

